### 1
# dodanie zdjęcia (nie profilowego) do katalogu (nie wymaga usera)
# @name uploadPhoto
POST http://localhost:3000/api/photos
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="view.jpg"
Content-Type: image/jpeg

< ./view.jpg
--boundary123--


@photoId = {{uploadPhoto.response.body.id}}


### 2
# otagowanie tego zdjęcia (widać pod /api/photos) (nie wymaga usera)
PATCH http://localhost:3000/api/photos/tags/mass
Content-Type: application/json

{
	"id": "{{photoId}}",
	"tags": ["woda", "krajobraz", "krakow"]
}


### GET dla punktu 2
GET http://localhost:3000/api/photos


### 3
# użycie filtra na tym zdjęciu i pobranie go (nie wymaga usera)-
# @name applyFilter
PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Type: application/json

{   
	"id": "{{photoId}}",
	"lastChange": "grayscale"
}

### GET dla punktu 3
GET http://localhost:3000/api/getimage?id={{photoId}}&filter=grayscale

### 4 rejestracja
# zarejestrowanie, logowanie i uzyskanie tokenu do autoryzacji usera (widać pod /api/user) 
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
	"name": "Mateusz",
	"lastName": "Makaryk",
	"email": "mmakaryk99@uczen.tl.krakow.pl",
	"password": "SuperHaslo123"
}

### 4 logowanie
# @name loginUser
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
	"email": "mmakaryk99@uczen.tl.krakow.pl",
	"password": "SuperHaslo123"
}

### GET dla punktu 4
GET http://localhost:3000/api/user HTTP/1.1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc4MTY5MjEyNzg0NiwiZW1haWwiOiJtbWFrYXJ5azk5QHVjemVuLnRsLmtyYWtvdy5wbCIsIm5hbWUiOiJNYXRldXN6IiwiaWF0IjoxNzgxNjkyMTMyLCJleHAiOjE3ODE3Nzg1MzJ9.G5QHo7jPLFR-TKJKGcrRtrSgz4xbTSWAaLMQJIga0WI
### 5
# aktualizacja danych osobowych usera, po autoryzacji tokenem (widać pod /api/user)
PATCH http://localhost:3000/api/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "Mateusz_zmienione_imie",
	"lastName": "Makaryk_zmienione_nazwisko"
}

### GET dla punktu 5
GET http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer {{token}}

### 6
# dodanie trzech wersji zdjęcia profilowego usera, po autoryzacji tokenem (widać pod /api/user) 
POST http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="user.png"
Content-Type: image/png

< ./user.png
------FormBoundary1234

### GET dla punktu 6
# Obecnie nie działa pod /api/user a pod /api/profile napraw to

### 7 pobranie tych danych (zdjęcia, dane osobowe) z poziomu rest clienta 
@ClientId = ID-12345
GET http://localhost:3000/api/profile
Authorization: Bearer {{token}}


### BroadCast punkt 8
# dowolny broadcast między zalogowanymi dwoma userami (SSE)
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
    "message": "Uwaga! To jest ważny komunikat dla wszystkich użytkowników!"
}

### Unicast po otagowaniu zdjęcia przez innego usera (nie działa jak narazie)
PATCH http://localhost:3000/api/photos/tags/mass
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"id": "{{photoId}}",
	"tags": ["zieleń", "orbita", "domek"]
}




###############################################################################
### PORADNIK I SEKRETY TESTOWANIA PUNKTU 9 (UNICAST SSE)
### W tym teście wcielasz się w rolę dwóch różnych osób:
###   - Użytkownik A (np. mmakaryk99@uczen.tl.krakow.pl) -> wrzuca zdjęcie i czeka w przeglądarce
###   - Użytkownik B (np. janusz@test.pl) -> loguje się w rest client i taguje zdjęcie Mateusza
###############################################################################

### KROK 1: Rejestracja Użytkownika B (Sprawcy / Tagującego)
### Musimy mieć drugie konto, żeby system wiedział, że to nie Ty sam siebie tagujesz!
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Janusz",
    "lastName": "Nosacz",
    "email": "janusz@test.pl",
    "password": "JanuszoweHaslo123"
}


### KROK 2: Logowanie Użytkownika B (Janusza)
### Wyślij to zapytanie i skopiuj jego wygenerowany token z odpowiedzi!
# @name loginUserB
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "janusz@test.pl",
    "password": "JanuszoweHaslo123"
}

### TUTAJ WKLEJASZ TOKEN JANUSZA (UŻYTKOWNIKA B), KTÓRY TUŻ PRZED CHWILĄ SKOPIOWAŁEŚ:
@tokenJanusza = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc4MTY5MjEwMDI2NSwiZW1haWwiOiJqYW51c3pAdGVzdC5wbCIsIm5hbWUiOiJKYW51c3oiLCJpYXQiOjE3ODE2OTIxMDcsImV4cCI6MTc4MTc3ODUwN30.SZYzsBITbS2B3HqP4GTiAdhfh4e6JNXFBzs8ZUuMg-Y


### KROK 3: Uruchomienie nasłuchiwania dla Mateusza (Użytkownika A)
### Instrukcja: 
### 1. Weź swój token Mateusza (ten z punktu 4 na samej górze pliku, zmienna {{token}}).
### 2. Otwórz nową kartę w przeglądarce i wklej tam link:
###    http://localhost:3000/api/notifications/subscribe?token=TWÓJ_TOKEN_MATEUSZA
### 3. Karta zacznie się ładować i pokaże obiekt z Twoim adresem email oraz clientId. 
### 4. NIE ZAMYKAJ TEJ KARTY. Zostaw ją otwartą na boku ekranu.


### KROK 4: Mateusz wrzuca zdjęcie (Musi być zalogowany, aby stać się autorem!)
### Wyślij to zapytanie używając swojego głównego tokenu ({{token}}).
# @name uploadPhotoByMateusz
POST http://localhost:3000/api/photos
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary12345

--boundary12345
Content-Disposition: form-data; name="file"; filename="view.jpg"
Content-Type: image/jpeg

< ./image.jpg
--boundary12345--


### Złapanie ID nowo utworzonego zdjęcia Mateusza
@photoIdMateusza = {{uploadPhotoByMateusz.response.body.id}}


### KROK 5: Janusz wkracza do akcji i taguje zdjęcie Mateusza!
### Zwróć uwagę, że w nagłówku podajemy {{tokenJanusza}}, ale tagujemy @photoIdMateusza.
PATCH http://localhost:3000/api/photos/tags/mass
Authorization: Bearer {{tokenJanusza}}
Content-Type: application/json

{
    "id": "{{photoIdMateusza}}",
    "tags": [
        {"name": "woda"}, 
        {"name": "niebo"}
    ]
}

### 💥 FINAŁ TESTU:
### W ułamku sekundy po wysłaniu powyższego zapytania PATCH, spójrz na kartę przeglądarki,
### którą otworzyłeś w KROKU 3. Powinien dopisać się tam automatycznie komunikat typu:
### data: {"type":"unicast","message":"user o <id: 171862534123> otagował Twoje zdjęcie","timestamp":"..."}