### 1
# dodanie zdjęcia (nie profilowego) do katalogu (nie wymaga usera)
# @name uploadPhoto
POST http://localhost:3000/api/photos
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="view.jpg"
Content-Type: image/jpeg

< ./view.jpg
--boundary123--


@photoId = {{uploadPhoto.response.body.id}}


### 2
# otagowanie tego zdjęcia (widać pod /api/photos) (nie wymaga usera)
PATCH http://localhost:3000/api/photos/tags
Content-Type: application/json

{
	"id": "{{photoId}}",
	"tags": ["woda", "krajobraz", "krakow"]
}


### GET dla punktu 2
GET http://localhost:3000/api/photos


### 3
# użycie filtra na tym zdjęciu i pobranie go (nie wymaga usera)
PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Type: application/json

{   
	"id": "{{photoId}}",
	"lastChange": "grayscale"
}

### GET dla punktu 3
GET http://localhost:3000/api/getimage/{{photoId}}/filter/grayscale

### 4 rejestracja
# zarejestrowanie, logowanie i uzyskanie tokenu do autoryzacji usera (widać pod /api/user) 
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
	"name": "Mateusz",
	"lastName": "Makaryk",
	"email": "mmakaryk99@uczen.tl.krakow.pl",
	"password": "SuperHaslo123"
}

### 4 logowanie
# @name loginUser
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
	"email": "mmakaryk99@uczen.tl.krakow.pl",
	"password": "SuperHaslo123"
}

### GET dla punktu 4
GET http://localhost:3000/api/user HTTP/1.1

@token = {{loginUser.response.body.token}}

### Aktualizacja danych
# aktualizacja danych osobowych usera, po autoryzacji tokenem (widać pod /api/user)
PATCH http://localhost:3000/api/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "Mateusz_zmienione_imie",
	"lastName": "Makaryk_zmienione_nazwisko"
}

### GET dla punktu 5
GET http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer {{token}}

### GET dla punktu 5
GET http://localhost:3000/api/user HTTP/1.1
Authorization: Bearer {{token}}

### 6
# dodanie trzech wersji zdjęcia profilowego usera, po autoryzacji tokenem (widać pod /api/user) 
POST http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="user.png"
Content-Type: image/png

< ./user.png
------FormBoundary1234

### GET dla punktu 6
GET http://localhost:3000/api/user HTTP/1.1

### 7 pobranie tych danych (zdjęcia, dane osobowe) z poziomu rest clienta 
@ClientId = ID-12345
GET http://localhost:3000/api/profile
Authorization: Bearer {{token}}


### BroadCast punkt 8
# dowolny broadcast między zalogowanymi dwoma userami (SSE)
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
    "message": "Uwaga! To jest ważny komunikat dla wszystkich użytkowników!"
}

### 9
### Rejestracja drugiego konta
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Janusz",
    "lastName": "Nosacz",
    "email": "janusz@test.pl",
    "password": "JanuszoweHaslo123"
}


### logowanie użytkownika Janusz
# @name loginUserB
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "janusz@test.pl",
    "password": "JanuszoweHaslo123"
}

@tokenJanusza = {{loginUserB.response.body.token}}

### Uploaduje zdjęcia jako mateusz
# @name uploadPhotoByMateusz
POST http://localhost:3000/api/photos
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundry12345

--boundry12345
Content-Disposition: form-data; name="file"; filename="view.jpg"
Content-Type: image/jpeg

< ./image.jpg
--boundry12345--

### Otagowanie zdjęcia użytkownikiem janusz
### Tagi
PATCH http://localhost:3000/api/photos/tags
Authorization: Bearer {{tokenJanusza}}
Content-Type: application/json

{
	"id": "1781712452923",
	"tags": ["woda", "krajobraz", "krakow"]
}

### Tag
PATCH http://localhost:3000/api/photos/tags
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"id": "1781712452923",
	"tag": ["retro"]
}


### ewentualny test unicast
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
    "to": "ID-OKW34",
    "message": "Mega tajna wiadomosc ale tylko dla Ciebie!"
}