### POST - 4.6 unieważnienie tokena na serwerze (czarna lista)
POST http://localhost:3000/api/user/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzgxNjM0MDA1LCJleHAiOjE3ODE2Mzc2MDV9.mIrCq_qVFZHD_hW-gCADELfiS4r2esr9psKK1MH0ep8