### POST - 4.1 rejestracja użytkownika
POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "name": "Janaaaa",
    "lastName": "Nowak",
    "email": "example2@example.com",
    "password": "mojeSuperHaslo123"
}