### TEST 1: BROADCAST (Wiadomość do wszystkich połączonych użytkowników)
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
    "message": "Uwaga! To jest ważny komunikat dla wszystkich użytkowników!"
}


### TEST 2: UNICAST (Wiadomość skierowana TYLKO do Ciebie)
# 🚨 WAŻNE: Podmień ID-A1B2C na identyfikator, który aktualnie widzisz w przeglądarce!
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
    "to": "ID-NAM9G",
    "message": "Cześć! Ta wiadomość powinna trafić tylko do Twojego okna."
}