### BROADCAST 
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
    "message": "Uwaga! To jest ważny komunikat dla wszystkich użytkowników!"
}


### UNICAST
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
    "to": "ID-NAM9G",
    "message": "Cześć! Ta wiadomość powinna trafić tylko do Twojego okna."
}